name: Validate Generator application

on:
  push:

jobs:
  test-generator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18 

    - name: Run Golang tests
      run: |
        cd app
        make test
