name: Lint Next.js App

on:
  push:

jobs:
  lint-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Run lint
      run: |
        cd client 
        chmod +x create-env.sh
        ./create-env.sh
        npm run lint
